### ISSUE TITLE
Question about data preparation

### ISSUE THREAD

**Issue by kvnsng** [matteorr/rel_3d_pose#2]
Hi! wonderful work. I was able to successfully clone and get the notebook running. 

I might be missing something in the paper, but it seems like you prepare 2D keypoints from an image and store in a numpy format. I'd like to test this with some random images in the wild, so my questions are:

1) What model do you use for making these 2D keypoints?
2) Could you provide some guidance on how to prepare the data??

I'd really appreciate your help!

**Comment by matteorr** [comment]
Glad you find our work useful! 

Yes, if you're trying to test a _pretrained_ model ([download here](https://github.com/matteorr/rel_3d_pose/tree/master/checkpoint)) on random images you just need to create a numpy array containing the 2D keypoints for those images and specify the path of the numpy array in the file [run_model.py](https://github.com/matteorr/rel_3d_pose/blob/master/run_model.py#L145).

It doesn't matter what method you use to obtain the 2D keypoints (you could even compute them manually - [check this](https://github.com/matteorr/rel_3d_pose/blob/master/demo_data/manual_keypoint_clicker.py)) as long as the numpy array respects the following properties:

- The array has shape `(N, 2 * num_keypoints)` where `N` is the number of distinct inputs you want to obtain the 3D pose of, and `num_keypoints` is the number of input keypoints that the model was pretrained with. 

- The `x` and `y` coordinates of the individual keypoints in the array are alternated. To state the obvious that means the coordinates will be organized like this: `[x_0, y_0, x_1, y_1, x_2, y_2, ...]`.

- The order of the specific keypoints for the input and output arrays (i.e. left_hip, right_shoulder, ...)  is specified in the file [misc.py](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/misc.py) which you can find in the folder [src/data_formats](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats). To find out what data format was used to train a specific model, you just need to look at the field `dataset_type` in its options file `opt.json`.

Please reopen if there's something you're still confused about!

---

**Additional details on the data formats.**

Our code contains the following data_formats. `file 1` is used for training purposes, `file 2` is used for visualization purposes.

- `human36_17k` ([file 1](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/misc.py#L164-L235), [file 2](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/human36_17k_config.py)): The standard 17 keypoints model used by most literature for experiments on the Human3.6M dataset.
- `lsp_14k`, `human36_14k` ([file 1](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/misc.py#L19-L91), [file 2](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/lsp_14k_config.py)): The 14 keypoints model defined in the LSP dataset (which we also used on the Human3.6M dataset).
- `openpose_17k` ([file 1](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/misc.py#L319-L396), [file 2](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/openpose_17k_config.py)): The 17 keypoints model defined by openpose (without eyes, ears and feet - [check this](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#keypoint-ordering)). 
- `human36_19k` ([file 1](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/misc.py#L237-L317), [file 2](https://github.com/matteorr/rel_3d_pose/blob/master/src/data_formats/human36_19k_config.py)): A 19 keypoints model defined on Human3.6M not used in the paper.

**NOTE**: All of our models have the same number and type of input (2D) and output (3D) keypoints. However, this is simply the implementation choice we made for our specific set of experiments and can be changed if needed ([related issue](https://github.com/una-dinosauria/3d-pose-baseline/issues/52)).
