### ISSUE TITLE
Question : Is it possible to test ones own videos ? 

### ISSUE THREAD

**Issue by timtensor** [matteorr/rel_3d_pose#3]
Hi , Is it possible to test with our own videos , that has 2d detections using posenet or open pose ? 
/Thanks 
Tim

**Comment by matteorr** [comment]
Yes, I would refer you to issue #2, which is very similar in nature. As long as the format of the 2D keypoints of your videos matches the input format of our network you can just use one of the pre-trained models.

Please let me know if you need more assistance.

**Comment by timtensor** [comment]
Hi, I tried to run the following using your pre trained model . I used posenet detection from  the following repo  :  [https://github.com/rwightman/posenet-python](url)  which returns the 17 keypoints, in the file 
`webcam_demo.py` in the following

 [https://github.com/rwightman/posenet-python/blob/1d8192833d816d78e0c7c58a9aa717cce73975cd/webcam_demo.py#L50](url) 

Which returns a 17 keypoint according to the following keypoint , structure  
`For Posenet 'nose', 0 'leftEye', 1 'rightEye', 2 'leftEar', 3 'rightEar', 4 'leftShoulder', 5 'rightShoulder', 6 'leftElbow', 7 'rightElbow', 8 'leftWrist', 9 'rightWrist', 10 'leftHip', 11 'rightHip', 12 'leftKnee', ' 13 rightKnee', 14 'leftAnkle', 15 'rightAnkle' 16`

However , i am not sure if this input would be enough to run it against the pre trained model . 

I have saved the array in the following  , i was wondering if this is right way to do so ? 

[https://drive.google.com/file/d/1Vhtnz67W7rgnRY7zYIIXZZSQdWIoS7Kk/view?usp=sharing](url)

**Comment by matteorr** [comment]
It would be useful if you could paste a code snippet showing what you tried and what isn't working.
As I mentioned in the above post, issue #2 should be pretty explanatory for running a pretrained model on a numpy data array. 

Please be more specific and I can try to help.
