### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lvandoit** [matteorr/rel_3d_pose#4]
HI：
   When i try your pre-trained module in my computer with linux using 'python run_model.py‘.But  i got the error as fllows:UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 3: ordinal not in range(128).I had try many way to solve the error,but any works.So,what should i  do?
@matteorr

**Comment by macaodha** [comment]
Hi @lvandoit,

What version of Python are you using? The code was developed using 2.7.

**Comment by matteorr** [comment]
I've seen a similar error when loading a model trained with python 2 while using python 3. This worked for me in the past:

```
if LOAD_MODEL_TRAINED_ON_PYHTON2:
    from functools import partial
    import pickle
    pickle.load = partial(pickle.load, encoding="latin1")
    pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")

    state_dict = torch.load(checkpoint_path, map_location=lambda storage, loc: storage, pickle_module=pickle)

else:
    state_dict = torch.load(checkpoint_path, map_location=lambda storage, loc: storage)
```

**Comment by lvandoit** [comment]
ihi:
   thanks,The problem arises precisely because of the python version.The code was developed using  python2.7,but mine is python3.7.The information of the error as follows:
Traceback (most recent call last):
  File "run_model.py", line 179, in <module>
    predicted_3d_poses = run_model(opt)
  File "run_model.py", line 51, in run_model
    ckpt    = torch.load(opt['load'],pickle_module=pickle)
  File "/home/weixy/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 369, in load
    return _load(f, map_location, pickle_module)
  File "/home/weixy/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 544, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 3: ordinal not in range(128)
So how can i solve this error?   @matteorr

**Comment by matteorr** [comment]
@lvandoit  - Did you try the code that I pasted above?

**Comment by lvandoit** [comment]
thanks,i had solve this error by another methods,and then when i run the main_human36.py ,got a error about having not the file of cameras.h5.Also it do not included in the source of code.So where should i get this file? @matteorr @macaodha

**Comment by macaodha** [comment]
You will need to download the Huaman3.6 [dataset](http://vision.imar.ro/human3.6m/description.php).

**Comment by lvandoit** [comment]
ok,thanks @macaodha
