### ISSUE TITLE
Mturk Data 

### ISSUE THREAD

**Issue by zhLawliet** [matteorr/rel_3d_pose#9]
@matteorr  where can i find the data?
# Mturk Data:
We list the links to download the crowd collected relative depth annotations and the merged version which we release as the Relative Depth LSP Dataset. Download and put them in this directory to replicate the experiments from our paper.

### Relative Depth LSP Dataset
 - Click [here](http://www.vision.caltech.edu/~mronchi/projects/RelativePose/#dataset) for info.
 - http://www.vision.caltech.edu/~mronchi/projects/RelativePose/Dataset/relative_depth_lsp_v1.json.zip

### Relative Depth LSP Raw Mturk Annotations
 - http://www.vision.caltech.edu/~mronchi/projects/RelativePose/Dataset/relative_depth_lsp_mturk.pkl.zip

### Relative Depth LSP Author Annotations
 - http://www.vision.caltech.edu/~mronchi/projects/RelativePose/Dataset/relative_depth_lsp_authors.pkl.zip

### Relative Depth Human3.6m Mturk User Study
 - http://www.vision.caltech.edu/~mronchi/projects/RelativePose/Dataset/relative_depth_human36m_user_study.pkl.zip

### Relative Depth Human3.6m Ground Truth
 - http://www.vision.caltech.edu/~mronchi/projects/RelativePose/Dataset/relative_depth_human36m_gt.json.zip

**Comment by elijahcole** [comment]
Sorry for the trouble, we are transitioning our datasets to new hosting. 

At the moment this data can be found here: https://data.caltech.edu/records/20096

**Comment by zhLawliet** [comment]
thanks
